title: Qwerui's Blog
lang: ko-KR
description: Qwerui's Blog
edit: false

copyright: false

addons:
  - github
  - gems
  - analytics

addons_commit: true

theme: null

# sort
readme_index:
  with_frontmatter: true

sass:
  style: compressed

exclude:
  - Makefile
  - Gemfile
  - Gemfile.lock
  - ci.sh
  - CODE_OF_CONDUCT.md
  - LICENSE
  - jekyll-rtd-theme.gemspec
  - images
